### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by rsadr** [rrrrhhhh123/delta-hedging#1]
TypeError: delta_hedging_methods() missing 1 required positional argument: 'one_side_cost'

When executing:

from deltaHedging import *

results = delta_hedging_methods(T_EXPIRATION, DAILY_STEPS, MU, IMPLIED_VOL, SPOT_0, STRIKE, INTEREST_RATE, OPTION_POSITION, OPTION_TYPE, MC_PATHS_NUM, ONE_SIDE_COST)
results['Zak_Band']

**Comment by rrrrhhhh123** [comment]
Sorry for the bug. I have fixed it and pushed the latest code.
